# ArDrive CLI v1 docker image 
# 2021-09-17_01          
#
#     
#     THIS IS A PRESERVATION IMAGE!
#     Though it is fully functional, production use is NOT recommended!
#     Use the upcoming v2 CLI instead.
#
#     This variation of the Dockerfile builds only ardrive-cli
#     without my support scripts.
#                 
#                                                
#     ArDrive CLI  by  ArDrive Team  (ardrive.io)       
#     Dockerfile   by  Silanael      (silanael.com)     
#
#     
#
# *** WARNING ***
#
#     - Wallets created with the CLI can be lost if they're saved
#       into the container instead of into volumes/bind mounts!
#
#     - This version of the CLI doesn't use bundles, so it is possible for
#       one transaction (data or metadata) to go through while the other one
#       gets dropped by the network, resulting in orphaned files/data.
#
#     - Permaweb is a powerful thing. Once you put something into it,
#       it's there for good. Consider VERY carefully what to upload.
#
#
# *** OTHER ISSUES ***
#
#     - The last time I checked, ardrive-cli threw an exception for
#       files larger than 2GB while still creating a metadata transaction.
#       Don't try your luck. v2 is right around the corner.
#
#     - ardrive-cli throws an exception if it's given a wallet path
#       that doesn't exist, yet it doesn't properly quit after this.
#
#
#  *** FOR THE FUTURE ***
#
#      This Dockerfile pulls the latest commit from the ardrive-cli repo,
#      which is the v1 CLI at the writing of this. When v2 is released,
#      this thing probably breaks - it should be fixable by pointing
#      the git clone-command to the v1-branch (that does not yet exist)
#      in case I forget to / don't feel like fixing it.              
#
#


FROM node:current-alpine

LABEL description="ArDrive CLI v1"                                       \
      author="Silanael"                                                  \
      com.silanael.usage="docker run -it -v datadir:/data <image>"       \
      com.silanael.url="silanael.com"                                    \
      com.silanael.e-mail="sila@silanael.com"                            \
      com.silanael.arweave="zPZe0p1Or5Kc0d7YhpT5kBC-JUPcDzUPJeMz2FdFiy4" \
      com.silanael.version="2021-09-17_01"


# Update the packages and install dependencies
RUN apk update && apk add make gcc g++ musl-dev python3 git bash

#RUN apt-get update && apt-get upgrade && apt autoremove -y && apt-get clean


# Install ardrive-cli
RUN git clone https://github.com/ardriveapp/ardrive-cli
WORKDIR /ardrive-cli
#RUN yarn


# Cleanup
#RUN yarn cache clean --all


# Use this is the other command fails
#CMD ["yarn", "run", "ardrive-cli", "2>/dev/null"]


# This produces less text clutter
#CMD ["/ardrive-cli/node_modules/.bin/ardrive-cli"]
