# ArDrive CLI v1 docker image 
# 2021-09-19_01          
#
#                                                                 
#     ArDrive CLI                    by  ArDrive Team  (ardrive.io)       
#     Dockerfile + support scripts   by  Silanael      (silanael.com)     
#
#
#
# *** VARIATIONS ***
#
#     Dockerfile        - Release version with safety/helper scripts.
#     Dockerfile-plain  - Standalone release version for those familiar with Docker and ardrive-cli.
#     Dockerfile-dev    - Development version pulled from https://github.com/ardriveapp/ardrive-cli
#
#     - The release version images are optimized for size and speed and are based on node-alpine.     
#     - The development image is single-stage and based on node-slim (Debian).
#
#
#
# *** WARNING ***
#
#     - THIS IS A PRESERVATION IMAGE!
#       Though it is fully functional, production use is NOT recommended!
#       Use the upcoming v2 CLI instead.
#
#     - Wallets created with the CLI can be lost if they're saved
#       into the container instead of into volumes/bind mounts!
#
#     - This version of the CLI doesn't use bundles, so it is possible for
#       one transaction (data or metadata) to go through while the other one
#       gets dropped by the network, resulting in orphaned data.
#
#     - Permaweb is a powerful thing. Once you put something into it,
#       it's there for good. Consider VERY carefully what to upload.
#
#
# *** OTHER ISSUES ***
#
#     - The last time I checked, ardrive-cli threw an exception for
#       files larger than 2GB while still creating a metadata transaction.
#       Don't try your luck. v2 is right around the corner.
#
#     - ardrive-cli throws an exception if it's given a wallet path
#       that doesn't exist, yet it doesn't properly quit after this.
#

FROM node:slim


LABEL description="ArDrive CLI - Dev image"                              \
      author="Silanael"                                                  \            
      com.silanael.url="silanael.com"                                    \
      com.silanael.e-mail="sila@silanael.com"                            \
      com.silanael.arweave="zPZe0p1Or5Kc0d7YhpT5kBC-JUPcDzUPJeMz2FdFiy4" \
      com.silanael.createdwith="nano, VS Code"                           \
      com.silanael.sys="Potato-01 MK3"                                   \                                
      com.silanael.version="2021-09-19_01"



# Update the packages
RUN apt-get update          && \
    apt-get upgrade         && \
    apt-get install git -y  && \
    apt-get clean
    


# Cloning only the latest commit - to get the full repository, remove "-- depth 1"
RUN git clone --depth 1 https://github.com/ardriveapp/ardrive-cli.git


# Build the project
WORKDIR /ardrive-cli
RUN yarn


CMD ["yarn", "start"]